version: '3.8'

services:
  pgdb:
    container_name: pgdb
    build:
      context: ./
      dockerfile: Dockerfile_PG
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  sqlserverdb:
    container_name: sqlserver
    build:
      context: ./
      dockerfile: Dockerfile_MS
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "YourStrongPassw0rd"
    ports:
      - "1433:1433"


volumes:
  postgres_data: